model: "unsloth/Qwen3-4B-Base-unsloth-bnb-4bit"
continued_training: False
access_token: null
output_dir: "dolphin-mistral-test"
stages:
  - name: gpt3
    until_step: 2000
    datasets:
      - path: "dolphin_gpt3_small.jsonl"
        weight: 1.0
  - name: gpt4
    until_step: 4000
    datasets:
      - path: "dolphin_gpt4_small.jsonl"
        weight: 1.0
val_dataset_file: null
lora_r: 32
lora_alpha: 64
lora_dropout: 0 # Any is okay, but 0 is optimized in unsloth
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"]
modules_to_save: ["embed_tokens", "lm_head"]
micro_batch_size: 1
gradient_accumulation_steps: 8
group_by_seq_len: false
max_grad_norm: 2.0
learning_rate: 0.00003
lr_scheduler_type: "cosine_with_restarts"
lr_scheduler_kwargs:
  num_cycles: 2
warmup_steps: 25
max_ctx_len: 2048
logging_steps: 1
eval_steps: 50
save_steps: 125 # Save intermediate checkpoints
save_total_limit: 8
add_imstart_token: True
map_eos_to_imend: True # Sometimes tokenizer does not work properly with *replaced* eos token, this is a workaround
load_in_4bit: False
cpu_offload_embeddings: True # Offload original embed_tokens and lm_head when they are in modules_to_save
